# Generated by Django 3.1.6 on 2021-02-18 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank='false', max_length=200)),
                ('slug', models.SlugField(blank='false')),
                ('poblacion', models.IntegerField(blank='false')),
            ],
            options={
                'verbose_name_plural': 'paises',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank='false', max_length=100)),
                ('slug', models.SlugField(blank='false')),
                ('foto', models.FileField(blank='false', upload_to='fotos/')),
                ('description', models.TextField(blank='false')),
                ('activa', models.BooleanField(default=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viaje.pais')),
            ],
            options={
                'verbose_name_plural': 'ciudades',
            },
        ),
    ]
